name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: DEV
    env: # Move env block here
      VITE_APP_API_KEY: ${{ secrets.VITE_APP_API_KEY }}
      VITE_APP_AUTH_DOMAIN: ${{ secrets.VITE_APP_AUTH_DOMAIN }}
      VITE_APP_PROJECT_ID: ${{ secrets.VITE_APP_PROJECT_ID }}
      VITE_APP_DATABASE_URL: ${{ secrets.VITE_APP_DATABASE_URL }}
      VITE_APP_STORAGE_BUCKET: ${{ secrets.VITE_APP_STORAGE_BUCKET }}
      VITE_APP_MESSAGING_SENDER_ID: ${{ secrets.VITE_APP_MESSAGING_SENDER_ID }}
      VITE_APP_APP_ID: ${{ secrets.VITE_APP_APP_ID }}
    steps:
      - uses: actions/checkout@v4

      # Log environment variables to ensure they are loaded
      - name: Check environment variables
        run: |
          echo "Checking environment variables..."
          env_vars=(VITE_APP_API_KEY VITE_APP_AUTH_DOMAIN VITE_APP_PROJECT_ID VITE_APP_DATABASE_URL VITE_APP_STORAGE_BUCKET VITE_APP_MESSAGING_SENDER_ID VITE_APP_APP_ID)
          for var in "${env_vars[@]}"; do
            if [ -z "${!var}" ]; then
              echo "ERROR: $var is not set or is empty."
              exit 1
            else
              echo "$var is set."
            fi
          done

      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHADE_OPTIMIZER_95D28 }}
          channelId: live
          projectId: shade-optimizer-95d28
